### ISSUE TITLE
illuminatio crashes on run

### ISSUE THREAD

**Issue by hacker-h** [inovex/illuminatio#52]
illuminatio crashes on `run` or `clean run` when running against a cluster with resources:
```
illuminatio clean run -o result.yml
Starting cleaning resources with policies ['on-request', 'always']
Deleting namespaces [] with cleanup policy on-request
Deleting namespaces [] with cleanup policy always
Deleting DSs in default with cleanup policy on-request
Deleting DSs in kube-node-lease with cleanup policy on-request
Deleting pods in default with cleanup policy on-request
Deleting pods in kube-node-lease with cleanup policy on-request
Deleting svcs in default with cleanup policy on-request
Deleting svcs in kube-node-lease with cleanup policy on-request
Deleting CfgMaps in default with cleanup policy on-request
Deleting CfgMaps in kube-node-lease with cleanup policy on-request
Deleting CRBs  with cleanup policy on-request globally
Deleting SAs in default with cleanup policy on-request
Deleting SAs in kube-node-lease with cleanup policy on-request
Deleting DSs in default with cleanup policy always
Deleting DSs in kube-node-lease with cleanup policy always
Deleting pods in default with cleanup policy always
Deleting pods in kube-node-lease with cleanup policy always
Deleting svcs in default with cleanup policy always
Deleting svcs in kube-node-lease with cleanup policy always
Deleting CfgMaps in default with cleanup policy always
Deleting CfgMaps in kube-node-lease with cleanup policy always
Deleting CRBs  with cleanup policy always globally
Deleting SAs in default with cleanup policy always
Deleting SAs in kube-node-lease with cleanup policy always
Finished cleanUp

Starting test generation and run.
Traceback (most recent call last):
  File "/home/hhaecker/virtualenvs/kspv/bin/illuminatio", line 11, in <module>
    load_entry_point('illuminatio==1.1.post0.dev32+g17fb87e', 'console_scripts', 'illuminatio')()
  File "/home/hhaecker/virtualenvs/kspv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hhaecker/virtualenvs/kspv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hhaecker/virtualenvs/kspv/lib/python3.5/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/hhaecker/virtualenvs/kspv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hhaecker/virtualenvs/kspv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hhaecker/virtualenvs/kspv/lib/python3.5/site-packages/illuminatio-1.1.post0.dev32+g17fb87e-py3.5.egg/illuminatio/illuminatio.py", line 75, in run
    cases, gen_run_times = generator.generate_test_cases(net_pols.items, orch.current_namespaces)
  File "/home/hhaecker/virtualenvs/kspv/lib/python3.5/site-packages/illuminatio-1.1.post0.dev32+g17fb87e-py3.5.egg/illuminatio/test_generator.py", line 91, in generate_test_cases
    other_hosts, namespaces)
  File "/home/hhaecker/virtualenvs/kspv/lib/python3.5/site-packages/illuminatio-1.1.post0.dev32+g17fb87e-py3.5.egg/illuminatio/test_generator.py", line 143, in generate_negative_cases_for_incoming_cases
    inverted_hosts = {h for l in {invert_host(host) for host in allowed_hosts} for h in l}
  File "/home/hhaecker/virtualenvs/kspv/lib/python3.5/site-packages/illuminatio-1.1.post0.dev32+g17fb87e-py3.5.egg/illuminatio/test_generator.py", line 143, in <setcomp>
    inverted_hosts = {h for l in {invert_host(host) for host in allowed_hosts} for h in l}
TypeError: unhashable type: 'list'
```

Resources have been created with the following manifest:
```
apiVersion: v1
kind: Namespace
metadata:
  name: 02-limit-traffic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: bookstore
    role: api
  name: apiserver
  namespace: 02-limit-traffic
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bookstore
      role: api
  template:
    metadata:
      labels:
        app: bookstore
        role: api
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: apiserver
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookstore
    role: api
  name: apiserver
  namespace: 02-limit-traffic
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bookstore
    role: api
  type: ClusterIP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: api-allow
  namespace: 02-limit-traffic
spec:
  podSelector:
    matchLabels:
      app: bookstore
      role: api
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: bookstore

```
