### ISSUE TITLE
Crash on prior run: unable to parse requirement: invalid label key \"*\"

### ISSUE THREAD

**Issue by claudev1** [inovex/illuminatio#98]
I use a local Kubernetes cluster deployed with Kind (kubernetes in docker).
Kubernetes version: 1.11.10
cni: Calico
illuminatio version: 1.3.2

Here is the debug trace:

> debug: DaemonSet 0/1 Pods are ready
debug: DaemonSet 0/1 Pods are ready
error: (400)
error: Reason: Bad Request
error: HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 05 May 2020 20:03:51 GMT', 'Content-Length': '409'})
error: HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"unable to parse requirement: invalid label key \"*\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')","reason":"BadRequest","code":400}
error: 
debug: Found following yamls in result config maps:[]
debug: Raw results: {}
debug: fromHostMappings: {'default:*': 'default:curl', 'illuminatio-inverted-staging:illuminatio-inverted-role=client-default': 'illuminatio-inverted-staging:illuminatio-dummy-hfc24', 'illuminatio-inverted-staging:role=client-default': 'illuminatio-inverted-staging:illuminatio-dummy-2945f', 'staging:illuminatio-inverted-role=client-default': 'staging:illuminatio-dummy-wxsz6', 'illuminatio-inverted-staging:*': 'illuminatio-inverted-staging:illuminatio-dummy-hfc24', 'illuminatio-inverted-role=admin:*': 'illuminatio-inverted-roleadmin:illuminatio-dummy-96sfl', 'staging:role=client-default': 'staging:curl-staging', 'staging:*': 'staging:backend', 'role=admin:*': 'roleadmin:illuminatio-dummy-628bn'}
debug: toHostMappings: {'default:*': {'default:*': 'default:svc-default-any'}, 'illuminatio-inverted-staging:illuminatio-inverted-role=client-default': {'staging:role=backend': 'staging:backend'}, 'illuminatio-inverted-staging:role=client-default': {'staging:role=backend': 'staging:backend'}, 'staging:illuminatio-inverted-role=client-default': {'staging:role=backend': 'staging:backend'}, 'illuminatio-inverted-staging:*': {'staging:role=frontend': 'staging:frontend'}, 'illuminatio-inverted-role=admin:*': {'staging:role=frontend': 'staging:frontend'}, 'staging:role=client-default': {'staging:role=backend': 'staging:backend'}, 'staging:*': {'staging:role=frontend': 'staging:frontend'}, 'role=admin:*': {'staging:role=frontend': 'staging:frontend'}}
debug: portMappings: {'default:*': {'default:*': {'-*': '-9128'}}, 'illuminatio-inverted-staging:illuminatio-inverted-role=client-default': {'staging:role=backend': {'-80': 'err'}}, 'illuminatio-inverted-staging:role=client-default': {'staging:role=backend': {'-80': 'err'}}, 'staging:illuminatio-inverted-role=client-default': {'staging:role=backend': {'-80': 'err'}}, 'illuminatio-inverted-staging:*': {'staging:role=frontend': {'-80': 'err'}}, 'illuminatio-inverted-role=admin:*': {'staging:role=frontend': {'-80': 'err'}}, 'staging:role=client-default': {'staging:role=backend': {'80': 'err'}}, 'staging:*': {'staging:role=frontend': {'80': 'err'}}, 'role=admin:*': {'staging:role=frontend': {'80': 'err'}}}
debug: port: -*
debug: mapped_port: -9128
debug: sender_pod: default:*
debug: receiver_pod: default:*
debug: mapped_sender_pod: default:curl
debug: mapped_receiver_pod: default:svc-default-any
debug: raw_results: {}
Traceback (most recent call last):
  File "/home/osboxes/.local/bin/illuminatio", line 10, in <module>
    sys.exit(cli())
  File "/home/osboxes/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/osboxes/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/osboxes/.local/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/osboxes/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/osboxes/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/osboxes/.local/lib/python3.7/site-packages/illuminatio/illuminatio.py", line 131, in run
    ) = execute_tests(cases, orch)
  File "/home/osboxes/.local/lib/python3.7/site-packages/illuminatio/illuminatio.py", line 202, in execute_tests
    raw_results, from_host_mappings, to_host_mappings, port_mappings
  File "/home/osboxes/.local/lib/python3.7/site-packages/illuminatio/illuminatio.py", line 241, in transform_results
    if mapped_port in raw_results[mapped_sender_pod][mapped_receiver_pod]:
KeyError: 'default:curl'

**Comment by johscheuer** [comment]
Could you share the following informations for debugging?

- How you started the kind cluster
- What NetworkPolicy did you apply
- How did you invoked illuminatio


Thanks for reporting the bug!

**Comment by claudev1** [comment]
Hi Johannes,

Thank you for getting in touch.

1. Kind cluster configuration:

Starting cluster: kind create cluster --image=kindest/node:v1.11.10 --config config-disable-cni.yml

with _config-disable-cni.yml:_
```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  disableDefaultCNI: true 
  podSubnet: 192.168.0.0/16 `
```
2. Network Policies

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: staging.backend
  namespace: staging
spec:
  podSelector:
    matchLabels:
      role: backend
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: client-default
    ports:
    - protocol: TCP
      port: 80
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: staging.frontend
  namespace: staging
spec:
  podSelector:
    matchLabels:
      role: frontend
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          role: admin
    ports:
    - protocol: TCP
      port: 80
  policyTypes:
  - Ingress
```

3. Illuminatio invocation
Installed with pip
```bash
$ illuminatio  run
```
